name: Publish executable

on: push

jobs:
  publish-executable:
    name: Publish executable
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: 6.x
      DOTNET_CONFIGURATION: Release
      DOTNET_PUBLISH_DIRECTORY_PATH: "${{ env.GITHUB_WORKSPACE }}/code/bin/dotnet-publish"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Publish .NET Core application
        run: dotnet publish "$GITHUB_WORKSPACE/code/run-test/run-test.csproj" --configuration "$DOTNET_CONFIGURATION" --runtime "win-x64" --self-contained "true" --output "$DOTNET_PUBLISH_DIRECTORY_PATH"
      - name: Upload application
        uses: actions/upload-artifact@v2
        with:
          name: run-test
          path: "$DOTNET_PUBLISH_DIRECTORY_PATH"
          if-no-files-found: error
